// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8tWm3W_SYVHyWSJH3u7CMHXltW_J3c2Y',
    appId: '1:870870389735:web:ac64b53c0ce5f3757ba342',
    messagingSenderId: '870870389735',
    projectId: 'renty-a5491',
    authDomain: 'renty-a5491.firebaseapp.com',
    storageBucket: 'renty-a5491.firebasestorage.app',
    measurementId: 'G-0C1LZEMF28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNz_8dsCV5UjTPwdoIZIbuhQaIGom3wWw',
    appId: '1:870870389735:android:593f217a684dccf37ba342',
    messagingSenderId: '870870389735',
    projectId: 'renty-a5491',
    storageBucket: 'renty-a5491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4JPUzu9zhIuxq0zEmuNf96CaM9DQAoc',
    appId: '1:870870389735:ios:2ca2036909a665637ba342',
    messagingSenderId: '870870389735',
    projectId: 'renty-a5491',
    storageBucket: 'renty-a5491.firebasestorage.app',
    iosBundleId: 'com.example.renty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4JPUzu9zhIuxq0zEmuNf96CaM9DQAoc',
    appId: '1:870870389735:ios:2ca2036909a665637ba342',
    messagingSenderId: '870870389735',
    projectId: 'renty-a5491',
    storageBucket: 'renty-a5491.firebasestorage.app',
    iosBundleId: 'com.example.renty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8tWm3W_SYVHyWSJH3u7CMHXltW_J3c2Y',
    appId: '1:870870389735:web:725f8a546b8214c47ba342',
    messagingSenderId: '870870389735',
    projectId: 'renty-a5491',
    authDomain: 'renty-a5491.firebaseapp.com',
    storageBucket: 'renty-a5491.firebasestorage.app',
    measurementId: 'G-27N8BKEHKW',
  );
}
